<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Zoker68\Shop\Models\Country;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        Country::insert([
            ['published' => 0, 'code' => 'AU', 'name' => 'Australia', 'phone_code' => 61],
            ['published' => 0, 'code' => 'CA', 'name' => 'Canada', 'phone_code' => 0],
            ['published' => 0, 'code' => 'GB', 'name' => 'United Kingdom', 'phone_code' => 44],
            ['published' => 0, 'code' => 'US', 'name' => 'United States', 'phone_code' => 1],
            ['published' => 0, 'code' => 'AF', 'name' => 'Afghanistan', 'phone_code' => 93],
            ['published' => 0, 'code' => 'AX', 'name' => 'Aland Islands ', 'phone_code' => 358],
            ['published' => 0, 'code' => 'AL', 'name' => 'Albania', 'phone_code' => 355],
            ['published' => 0, 'code' => 'DZ', 'name' => 'Algeria', 'phone_code' => 213],
            ['published' => 0, 'code' => 'AS', 'name' => 'American Samoa', 'phone_code' => 1684],
            ['published' => 0, 'code' => 'AD', 'name' => 'Andorra', 'phone_code' => 376],
            ['published' => 0, 'code' => 'AO', 'name' => 'Angola', 'phone_code' => 244],
            ['published' => 0, 'code' => 'AI', 'name' => 'Anguilla', 'phone_code' => 1264],
            ['published' => 0, 'code' => 'AQ', 'name' => 'Antarctica', 'phone_code' => 672],
            ['published' => 0, 'code' => 'AG', 'name' => 'Antigua and Barbuda', 'phone_code' => 1268],
            ['published' => 0, 'code' => 'AR', 'name' => 'Argentina', 'phone_code' => 54],
            ['published' => 0, 'code' => 'AM', 'name' => 'Armenia', 'phone_code' => 374],
            ['published' => 0, 'code' => 'AW', 'name' => 'Aruba', 'phone_code' => 297],
            ['published' => 1, 'code' => 'AT', 'name' => 'Austria', 'phone_code' => 43],
            ['published' => 0, 'code' => 'AZ', 'name' => 'Azerbaijan', 'phone_code' => 994],
            ['published' => 0, 'code' => 'BS', 'name' => 'Bahamas', 'phone_code' => 1242],
            ['published' => 0, 'code' => 'BH', 'name' => 'Bahrain', 'phone_code' => 973],
            ['published' => 0, 'code' => 'BD', 'name' => 'Bangladesh', 'phone_code' => 880],
            ['published' => 0, 'code' => 'BB', 'name' => 'Barbados', 'phone_code' => 1246],
            ['published' => 0, 'code' => 'BY', 'name' => 'Belarus', 'phone_code' => 375],
            ['published' => 0, 'code' => 'BE', 'name' => 'Belgium', 'phone_code' => 32],
            ['published' => 0, 'code' => 'BZ', 'name' => 'Belize', 'phone_code' => 501],
            ['published' => 0, 'code' => 'BJ', 'name' => 'Benin', 'phone_code' => 229],
            ['published' => 0, 'code' => 'BM', 'name' => 'Bermuda', 'phone_code' => 1441],
            ['published' => 0, 'code' => 'BT', 'name' => 'Bhutan', 'phone_code' => 975],
            ['published' => 0, 'code' => 'BO', 'name' => 'Bolivia, Plurinational State of', 'phone_code' => 591],
            ['published' => 0, 'code' => 'BQ', 'name' => 'Bonaire, Sint Eustatius and Saba', 'phone_code' => 599],
            ['published' => 0, 'code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'phone_code' => 387],
            ['published' => 0, 'code' => 'BW', 'name' => 'Botswana', 'phone_code' => 267],
            ['published' => 0, 'code' => 'BV', 'name' => 'Bouvet Island', 'phone_code' => 55],
            ['published' => 0, 'code' => 'BR', 'name' => 'Brazil', 'phone_code' => 55],
            ['published' => 0, 'code' => 'IO', 'name' => 'British Indian Ocean Territory', 'phone_code' => 246],
            ['published' => 0, 'code' => 'BN', 'name' => 'Brunei Darussalam', 'phone_code' => 673],
            ['published' => 0, 'code' => 'BG', 'name' => 'Bulgaria', 'phone_code' => 359],
            ['published' => 0, 'code' => 'BF', 'name' => 'Burkina Faso', 'phone_code' => 226],
            ['published' => 0, 'code' => 'BI', 'name' => 'Burundi', 'phone_code' => 257],
            ['published' => 0, 'code' => 'KH', 'name' => 'Cambodia', 'phone_code' => 855],
            ['published' => 0, 'code' => 'CM', 'name' => 'Cameroon', 'phone_code' => 237],
            ['published' => 0, 'code' => 'CV', 'name' => 'Cape Verde', 'phone_code' => 238],
            ['published' => 0, 'code' => 'KY', 'name' => 'Cayman Islands', 'phone_code' => 1345],
            ['published' => 0, 'code' => 'CF', 'name' => 'Central African Republic', 'phone_code' => 236],
            ['published' => 0, 'code' => 'TD', 'name' => 'Chad', 'phone_code' => 235],
            ['published' => 0, 'code' => 'CL', 'name' => 'Chile', 'phone_code' => 56],
            ['published' => 0, 'code' => 'CN', 'name' => 'China', 'phone_code' => 86],
            ['published' => 0, 'code' => 'CX', 'name' => 'Christmas Island', 'phone_code' => 61],
            ['published' => 0, 'code' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'phone_code' => 61],
            ['published' => 0, 'code' => 'CO', 'name' => 'Colombia', 'phone_code' => 57],
            ['published' => 0, 'code' => 'KM', 'name' => 'Comoros', 'phone_code' => 269],
            ['published' => 0, 'code' => 'CG', 'name' => 'Congo', 'phone_code' => 242],
            ['published' => 0, 'code' => 'CD', 'name' => 'Congo, the Democratic Republic of the', 'phone_code' => 243],
            ['published' => 0, 'code' => 'CK', 'name' => 'Cook Islands', 'phone_code' => 682],
            ['published' => 0, 'code' => 'CR', 'name' => 'Costa Rica', 'phone_code' => 506],
            ['published' => 0, 'code' => 'CI', 'name' => 'Cote d\'Ivoire', 'phone_code' => 225],
            ['published' => 1, 'code' => 'HR', 'name' => 'Croatia', 'phone_code' => 385],
            ['published' => 0, 'code' => 'CU', 'name' => 'Cuba', 'phone_code' => 53],
            ['published' => 0, 'code' => 'CW', 'name' => 'Curaçao', 'phone_code' => 599],
            ['published' => 0, 'code' => 'CY', 'name' => 'Cyprus', 'phone_code' => 357],
            ['published' => 0, 'code' => 'CZ', 'name' => 'Czech Republic', 'phone_code' => 420],
            ['published' => 0, 'code' => 'DK', 'name' => 'Denmark', 'phone_code' => 45],
            ['published' => 0, 'code' => 'DJ', 'name' => 'Djibouti', 'phone_code' => 253],
            ['published' => 0, 'code' => 'DM', 'name' => 'Dominica', 'phone_code' => 1767],
            ['published' => 0, 'code' => 'DO', 'name' => 'Dominican Republic', 'phone_code' => 1809],
            ['published' => 0, 'code' => 'EC', 'name' => 'Ecuador', 'phone_code' => 593],
            ['published' => 0, 'code' => 'EG', 'name' => 'Egypt', 'phone_code' => 20],
            ['published' => 0, 'code' => 'SV', 'name' => 'El Salvador', 'phone_code' => 503],
            ['published' => 0, 'code' => 'GQ', 'name' => 'Equatorial Guinea', 'phone_code' => 240],
            ['published' => 0, 'code' => 'ER', 'name' => 'Eritrea', 'phone_code' => 291],
            ['published' => 0, 'code' => 'EE', 'name' => 'Estonia', 'phone_code' => 372],
            ['published' => 0, 'code' => 'ET', 'name' => 'Ethiopia', 'phone_code' => 251],
            ['published' => 0, 'code' => 'FK', 'name' => 'Falkland Islands (Malvinas)', 'phone_code' => 500],
            ['published' => 0, 'code' => 'FO', 'name' => 'Faroe Islands', 'phone_code' => 298],
            ['published' => 0, 'code' => 'FI', 'name' => 'Finland', 'phone_code' => 358],
            ['published' => 0, 'code' => 'FJ', 'name' => 'Fiji', 'phone_code' => 679],
            ['published' => 0, 'code' => 'FR', 'name' => 'France', 'phone_code' => 33],
            ['published' => 0, 'code' => 'GF', 'name' => 'French Guiana', 'phone_code' => 594],
            ['published' => 0, 'code' => 'PF', 'name' => 'French Polynesia', 'phone_code' => 689],
            ['published' => 0, 'code' => 'TF', 'name' => 'French Southern Territories', 'phone_code' => 262],
            ['published' => 0, 'code' => 'GA', 'name' => 'Gabon', 'phone_code' => 241],
            ['published' => 0, 'code' => 'GM', 'name' => 'Gambia', 'phone_code' => 220],
            ['published' => 0, 'code' => 'GE', 'name' => 'Georgia', 'phone_code' => 995],
            ['published' => 0, 'code' => 'DE', 'name' => 'Germany', 'phone_code' => 49],
            ['published' => 0, 'code' => 'GH', 'name' => 'Ghana', 'phone_code' => 233],
            ['published' => 0, 'code' => 'GI', 'name' => 'Gibraltar', 'phone_code' => 350],
            ['published' => 0, 'code' => 'GR', 'name' => 'Greece', 'phone_code' => 30],
            ['published' => 0, 'code' => 'GL', 'name' => 'Greenland', 'phone_code' => 299],
            ['published' => 0, 'code' => 'GD', 'name' => 'Grenada', 'phone_code' => 1473],
            ['published' => 0, 'code' => 'GP', 'name' => 'Guadeloupe', 'phone_code' => 590],
            ['published' => 0, 'code' => 'GU', 'name' => 'Guam', 'phone_code' => 1671],
            ['published' => 0, 'code' => 'GT', 'name' => 'Guatemala', 'phone_code' => 502],
            ['published' => 0, 'code' => 'GG', 'name' => 'Guernsey', 'phone_code' => 44],
            ['published' => 0, 'code' => 'GN', 'name' => 'Guinea', 'phone_code' => 224],
            ['published' => 0, 'code' => 'GW', 'name' => 'Guinea-Bissau', 'phone_code' => 245],
            ['published' => 0, 'code' => 'GY', 'name' => 'Guyana', 'phone_code' => 592],
            ['published' => 0, 'code' => 'HT', 'name' => 'Haiti', 'phone_code' => 509],
            ['published' => 0, 'code' => 'HM', 'name' => 'Heard Island and McDonald Islands', 'phone_code' => 672],
            ['published' => 0, 'code' => 'VA', 'name' => 'Holy See (Vatican City State)', 'phone_code' => 39],
            ['published' => 0, 'code' => 'HN', 'name' => 'Honduras', 'phone_code' => 504],
            ['published' => 0, 'code' => 'HK', 'name' => 'Hong Kong', 'phone_code' => 852],
            ['published' => 1, 'code' => 'HU', 'name' => 'Hungary', 'phone_code' => 36],
            ['published' => 0, 'code' => 'IS', 'name' => 'Iceland', 'phone_code' => 354],
            ['published' => 0, 'code' => 'IN', 'name' => 'India', 'phone_code' => 91],
            ['published' => 0, 'code' => 'ID', 'name' => 'Indonesia', 'phone_code' => 62],
            ['published' => 0, 'code' => 'IR', 'name' => 'Iran, Islamic Republic of', 'phone_code' => 98],
            ['published' => 0, 'code' => 'IQ', 'name' => 'Iraq', 'phone_code' => 964],
            ['published' => 0, 'code' => 'IE', 'name' => 'Ireland', 'phone_code' => 353],
            ['published' => 0, 'code' => 'IM', 'name' => 'Isle of Man', 'phone_code' => 44],
            ['published' => 0, 'code' => 'IL', 'name' => 'Israel', 'phone_code' => 972],
            ['published' => 1, 'code' => 'IT', 'name' => 'Italy', 'phone_code' => 39],
            ['published' => 0, 'code' => 'JM', 'name' => 'Jamaica', 'phone_code' => 1876],
            ['published' => 0, 'code' => 'JP', 'name' => 'Japan', 'phone_code' => 81],
            ['published' => 0, 'code' => 'JE', 'name' => 'Jersey', 'phone_code' => 44],
            ['published' => 0, 'code' => 'JO', 'name' => 'Jordan', 'phone_code' => 962],
            ['published' => 0, 'code' => 'KZ', 'name' => 'Kazakhstan', 'phone_code' => 7],
            ['published' => 0, 'code' => 'KE', 'name' => 'Kenya', 'phone_code' => 254],
            ['published' => 0, 'code' => 'KI', 'name' => 'Kiribati', 'phone_code' => 686],
            ['published' => 0, 'code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of', 'phone_code' => 850],
            ['published' => 0, 'code' => 'KR', 'name' => 'Korea, Republic of', 'phone_code' => 82],
            ['published' => 0, 'code' => 'KW', 'name' => 'Kuwait', 'phone_code' => 965],
            ['published' => 0, 'code' => 'KG', 'name' => 'Kyrgyzstan', 'phone_code' => 996],
            ['published' => 0, 'code' => 'LA', 'name' => 'Lao People\'s Democratic Republic', 'phone_code' => 856],
            ['published' => 0, 'code' => 'LV', 'name' => 'Latvia', 'phone_code' => 371],
            ['published' => 0, 'code' => 'LB', 'name' => 'Lebanon', 'phone_code' => 961],
            ['published' => 0, 'code' => 'LS', 'name' => 'Lesotho', 'phone_code' => 266],
            ['published' => 0, 'code' => 'LR', 'name' => 'Liberia', 'phone_code' => 231],
            ['published' => 0, 'code' => 'LY', 'name' => 'Libyan Arab Jamahiriya', 'phone_code' => 218],
            ['published' => 0, 'code' => 'LI', 'name' => 'Liechtenstein', 'phone_code' => 423],
            ['published' => 0, 'code' => 'LT', 'name' => 'Lithuania', 'phone_code' => 370],
            ['published' => 0, 'code' => 'LU', 'name' => 'Luxembourg', 'phone_code' => 352],
            ['published' => 0, 'code' => 'MO', 'name' => 'Macao', 'phone_code' => 853],
            ['published' => 0, 'code' => 'MK', 'name' => 'North Macedonia', 'phone_code' => 389],
            ['published' => 0, 'code' => 'MG', 'name' => 'Madagascar', 'phone_code' => 261],
            ['published' => 0, 'code' => 'MW', 'name' => 'Malawi', 'phone_code' => 265],
            ['published' => 0, 'code' => 'MY', 'name' => 'Malaysia', 'phone_code' => 60],
            ['published' => 0, 'code' => 'MV', 'name' => 'Maldives', 'phone_code' => 960],
            ['published' => 0, 'code' => 'ML', 'name' => 'Mali', 'phone_code' => 223],
            ['published' => 0, 'code' => 'MT', 'name' => 'Malta', 'phone_code' => 356],
            ['published' => 0, 'code' => 'MH', 'name' => 'Marshall Islands', 'phone_code' => 692],
            ['published' => 0, 'code' => 'MQ', 'name' => 'Martinique', 'phone_code' => 596],
            ['published' => 0, 'code' => 'MR', 'name' => 'Mauritania', 'phone_code' => 222],
            ['published' => 0, 'code' => 'MU', 'name' => 'Mauritius', 'phone_code' => 230],
            ['published' => 0, 'code' => 'YT', 'name' => 'Mayotte', 'phone_code' => 262],
            ['published' => 0, 'code' => 'MX', 'name' => 'Mexico', 'phone_code' => 52],
            ['published' => 0, 'code' => 'FM', 'name' => 'Micronesia, Federated States of', 'phone_code' => 691],
            ['published' => 0, 'code' => 'MD', 'name' => 'Moldova, Republic of', 'phone_code' => 373],
            ['published' => 0, 'code' => 'MC', 'name' => 'Monaco', 'phone_code' => 377],
            ['published' => 0, 'code' => 'MN', 'name' => 'Mongolia', 'phone_code' => 976],
            ['published' => 0, 'code' => 'ME', 'name' => 'Montenegro', 'phone_code' => 382],
            ['published' => 0, 'code' => 'MS', 'name' => 'Montserrat', 'phone_code' => 1664],
            ['published' => 0, 'code' => 'MA', 'name' => 'Morocco', 'phone_code' => 212],
            ['published' => 0, 'code' => 'MZ', 'name' => 'Mozambique', 'phone_code' => 258],
            ['published' => 0, 'code' => 'MM', 'name' => 'Myanmar', 'phone_code' => 95],
            ['published' => 0, 'code' => 'NA', 'name' => 'Namibia', 'phone_code' => 264],
            ['published' => 0, 'code' => 'NR', 'name' => 'Nauru', 'phone_code' => 674],
            ['published' => 0, 'code' => 'NP', 'name' => 'Nepal', 'phone_code' => 977],
            ['published' => 0, 'code' => 'NL', 'name' => 'Netherlands', 'phone_code' => 31],
            ['published' => 0, 'code' => 'NC', 'name' => 'New Caledonia', 'phone_code' => 687],
            ['published' => 0, 'code' => 'NZ', 'name' => 'New Zealand', 'phone_code' => 64],
            ['published' => 0, 'code' => 'NI', 'name' => 'Nicaragua', 'phone_code' => 505],
            ['published' => 0, 'code' => 'NE', 'name' => 'Niger', 'phone_code' => 227],
            ['published' => 0, 'code' => 'NG', 'name' => 'Nigeria', 'phone_code' => 234],
            ['published' => 0, 'code' => 'NU', 'name' => 'Niue', 'phone_code' => 683],
            ['published' => 0, 'code' => 'NF', 'name' => 'Norfolk Island', 'phone_code' => 672],
            ['published' => 0, 'code' => 'MP', 'name' => 'Northern Mariana Islands', 'phone_code' => 1670],
            ['published' => 0, 'code' => 'NO', 'name' => 'Norway', 'phone_code' => 47],
            ['published' => 0, 'code' => 'OM', 'name' => 'Oman', 'phone_code' => 968],
            ['published' => 0, 'code' => 'PK', 'name' => 'Pakistan', 'phone_code' => 92],
            ['published' => 0, 'code' => 'PW', 'name' => 'Palau', 'phone_code' => 680],
            ['published' => 0, 'code' => 'PS', 'name' => 'Palestine', 'phone_code' => 970],
            ['published' => 0, 'code' => 'PA', 'name' => 'Panama', 'phone_code' => 507],
            ['published' => 0, 'code' => 'PG', 'name' => 'Papua New Guinea', 'phone_code' => 675],
            ['published' => 0, 'code' => 'PY', 'name' => 'Paraguay', 'phone_code' => 595],
            ['published' => 0, 'code' => 'PE', 'name' => 'Peru', 'phone_code' => 51],
            ['published' => 0, 'code' => 'PH', 'name' => 'Philippines', 'phone_code' => 63],
            ['published' => 0, 'code' => 'PN', 'name' => 'Pitcairn', 'phone_code' => 870],
            ['published' => 0, 'code' => 'PL', 'name' => 'Poland', 'phone_code' => 48],
            ['published' => 0, 'code' => 'PT', 'name' => 'Portugal', 'phone_code' => 351],
            ['published' => 0, 'code' => 'PR', 'name' => 'Puerto Rico', 'phone_code' => 1],
            ['published' => 0, 'code' => 'QA', 'name' => 'Qatar', 'phone_code' => 974],
            ['published' => 0, 'code' => 'RE', 'name' => 'Reunion', 'phone_code' => 262],
            ['published' => 0, 'code' => 'RO', 'name' => 'Romania', 'phone_code' => 40],
            ['published' => 1, 'code' => 'RU', 'name' => 'Russian Federation', 'phone_code' => 7],
            ['published' => 0, 'code' => 'RW', 'name' => 'Rwanda', 'phone_code' => 250],
            ['published' => 0, 'code' => 'BL', 'name' => 'Saint Barthélemy', 'phone_code' => 590],
            ['published' => 0, 'code' => 'SH', 'name' => 'Saint Helena', 'phone_code' => 290],
            ['published' => 0, 'code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'phone_code' => 1869],
            ['published' => 0, 'code' => 'LC', 'name' => 'Saint Lucia', 'phone_code' => 1758],
            ['published' => 0, 'code' => 'MF', 'name' => 'Saint Martin (French part)', 'phone_code' => 1599],
            ['published' => 0, 'code' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'phone_code' => 508],
            ['published' => 0, 'code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'phone_code' => 1784],
            ['published' => 0, 'code' => 'WS', 'name' => 'Samoa', 'phone_code' => 685],
            ['published' => 0, 'code' => 'SM', 'name' => 'San Marino', 'phone_code' => 378],
            ['published' => 0, 'code' => 'ST', 'name' => 'Sao Tome and Principe', 'phone_code' => 239],
            ['published' => 0, 'code' => 'SA', 'name' => 'Saudi Arabia', 'phone_code' => 966],
            ['published' => 0, 'code' => 'SN', 'name' => 'Senegal', 'phone_code' => 221],
            ['published' => 0, 'code' => 'RS', 'name' => 'Serbia', 'phone_code' => 381],
            ['published' => 0, 'code' => 'SC', 'name' => 'Seychelles', 'phone_code' => 248],
            ['published' => 0, 'code' => 'SL', 'name' => 'Sierra Leone', 'phone_code' => 232],
            ['published' => 0, 'code' => 'SG', 'name' => 'Singapore', 'phone_code' => 65],
            ['published' => 0, 'code' => 'SX', 'name' => 'Sint Maarten (Dutch part)', 'phone_code' => 599],
            ['published' => 0, 'code' => 'SK', 'name' => 'Slovakia', 'phone_code' => 421],
            ['published' => 1, 'code' => 'SI', 'name' => 'Slovenia', 'phone_code' => 386],
            ['published' => 0, 'code' => 'SB', 'name' => 'Solomon Islands', 'phone_code' => 677],
            ['published' => 0, 'code' => 'SO', 'name' => 'Somalia', 'phone_code' => 252],
            ['published' => 0, 'code' => 'ZA', 'name' => 'South Africa', 'phone_code' => 27],
            ['published' => 0, 'code' => 'GS', 'name' => 'South Georgia and the South Sandwich Islands', 'phone_code' => 500],
            ['published' => 0, 'code' => 'ES', 'name' => 'Spain', 'phone_code' => 34],
            ['published' => 0, 'code' => 'LK', 'name' => 'Sri Lanka', 'phone_code' => 94],
            ['published' => 0, 'code' => 'SD', 'name' => 'Sudan', 'phone_code' => 249],
            ['published' => 0, 'code' => 'SR', 'name' => 'Suriname', 'phone_code' => 597],
            ['published' => 0, 'code' => 'SJ', 'name' => 'Svalbard and Jan Mayen', 'phone_code' => 47],
            ['published' => 0, 'code' => 'SZ', 'name' => 'Swaziland', 'phone_code' => 268],
            ['published' => 0, 'code' => 'SE', 'name' => 'Sweden', 'phone_code' => 46],
            ['published' => 0, 'code' => 'CH', 'name' => 'Switzerland', 'phone_code' => 41],
            ['published' => 0, 'code' => 'SY', 'name' => 'Syrian Arab Republic', 'phone_code' => 963],
            ['published' => 0, 'code' => 'TW', 'name' => 'Taiwan, Province of China', 'phone_code' => 886],
            ['published' => 0, 'code' => 'TJ', 'name' => 'Tajikistan', 'phone_code' => 992],
            ['published' => 0, 'code' => 'TZ', 'name' => 'Tanzania, United Republic of', 'phone_code' => 255],
            ['published' => 0, 'code' => 'TH', 'name' => 'Thailand', 'phone_code' => 66],
            ['published' => 0, 'code' => 'TL', 'name' => 'Timor-Leste', 'phone_code' => 670],
            ['published' => 0, 'code' => 'TG', 'name' => 'Togo', 'phone_code' => 228],
            ['published' => 0, 'code' => 'TK', 'name' => 'Tokelau', 'phone_code' => 690],
            ['published' => 0, 'code' => 'TO', 'name' => 'Tonga', 'phone_code' => 676],
            ['published' => 0, 'code' => 'TT', 'name' => 'Trinidad and Tobago', 'phone_code' => 1868],
            ['published' => 0, 'code' => 'TN', 'name' => 'Tunisia', 'phone_code' => 216],
            ['published' => 0, 'code' => 'TR', 'name' => 'Turkey', 'phone_code' => 90],
            ['published' => 0, 'code' => 'TM', 'name' => 'Turkmenistan', 'phone_code' => 993],
            ['published' => 0, 'code' => 'TC', 'name' => 'Turks and Caicos Islands', 'phone_code' => 1649],
            ['published' => 0, 'code' => 'TV', 'name' => 'Tuvalu', 'phone_code' => 688],
            ['published' => 0, 'code' => 'UG', 'name' => 'Uganda', 'phone_code' => 256],
            ['published' => 0, 'code' => 'UA', 'name' => 'Ukraine', 'phone_code' => 380],
            ['published' => 0, 'code' => 'AE', 'name' => 'United Arab Emirates', 'phone_code' => 971],
            ['published' => 0, 'code' => 'UM', 'name' => 'United States Minor Outlying Islands', 'phone_code' => 246],
            ['published' => 0, 'code' => 'UY', 'name' => 'Uruguay', 'phone_code' => 598],
            ['published' => 0, 'code' => 'UZ', 'name' => 'Uzbekistan', 'phone_code' => 998],
            ['published' => 0, 'code' => 'VU', 'name' => 'Vanuatu', 'phone_code' => 678],
            ['published' => 0, 'code' => 'VE', 'name' => 'Venezuela, Bolivarian Republic of', 'phone_code' => 58],
            ['published' => 0, 'code' => 'VN', 'name' => 'Viet Nam', 'phone_code' => 84],
            ['published' => 0, 'code' => 'VG', 'name' => 'Virgin Islands, British', 'phone_code' => 1284],
            ['published' => 0, 'code' => 'VI', 'name' => 'Virgin Islands, U.S.', 'phone_code' => 1340],
            ['published' => 0, 'code' => 'WF', 'name' => 'Wallis and Futuna', 'phone_code' => 681],
            ['published' => 0, 'code' => 'EH', 'name' => 'Western Sahara', 'phone_code' => 212],
            ['published' => 0, 'code' => 'YE', 'name' => 'Yemen', 'phone_code' => 967],
            ['published' => 0, 'code' => 'ZM', 'name' => 'Zambia', 'phone_code' => 260],
            ['published' => 0, 'code' => 'ZW', 'name' => 'Zimbabwe', 'phone_code' => 263],
        ]);

        $us = Country::whereCode('US')->first();
        $us->regions()->createMany([
            ['code' => 'AL', 'name' => 'Alabama'],
            ['code' => 'AK', 'name' => 'Alaska'],
            ['code' => 'AS', 'name' => 'American Samoa'],
            ['code' => 'AZ', 'name' => 'Arizona'],
            ['code' => 'AR', 'name' => 'Arkansas'],
            ['code' => 'CA', 'name' => 'California'],
            ['code' => 'CO', 'name' => 'Colorado'],
            ['code' => 'CT', 'name' => 'Connecticut'],
            ['code' => 'DE', 'name' => 'Delaware'],
            ['code' => 'DC', 'name' => 'Dist. of Columbia'],
            ['code' => 'FL', 'name' => 'Florida'],
            ['code' => 'GA', 'name' => 'Georgia'],
            ['code' => 'GU', 'name' => 'Guam'],
            ['code' => 'HI', 'name' => 'Hawaii'],
            ['code' => 'ID', 'name' => 'Idaho'],
            ['code' => 'IL', 'name' => 'Illinois'],
            ['code' => 'IN', 'name' => 'Indiana'],
            ['code' => 'IA', 'name' => 'Iowa'],
            ['code' => 'KS', 'name' => 'Kansas'],
            ['code' => 'KY', 'name' => 'Kentucky'],
            ['code' => 'LA', 'name' => 'Louisiana'],
            ['code' => 'ME', 'name' => 'Maine'],
            ['code' => 'MD', 'name' => 'Maryland'],
            ['code' => 'MH', 'name' => 'Marshall Islands'],
            ['code' => 'MA', 'name' => 'Massachusetts'],
            ['code' => 'MI', 'name' => 'Michigan'],
            ['code' => 'FM', 'name' => 'Micronesia'],
            ['code' => 'MN', 'name' => 'Minnesota'],
            ['code' => 'MS', 'name' => 'Mississippi'],
            ['code' => 'MO', 'name' => 'Missouri'],
            ['code' => 'MT', 'name' => 'Montana'],
            ['code' => 'NE', 'name' => 'Nebraska'],
            ['code' => 'NV', 'name' => 'Nevada'],
            ['code' => 'NH', 'name' => 'New Hampshire'],
            ['code' => 'NJ', 'name' => 'New Jersey'],
            ['code' => 'NM', 'name' => 'New Mexico'],
            ['code' => 'NY', 'name' => 'New York'],
            ['code' => 'NC', 'name' => 'North Carolina'],
            ['code' => 'ND', 'name' => 'North Dakota'],
            ['code' => 'MP', 'name' => 'Northern Marianas'],
            ['code' => 'OH', 'name' => 'Ohio'],
            ['code' => 'OK', 'name' => 'Oklahoma'],
            ['code' => 'OR', 'name' => 'Oregon'],
            ['code' => 'PW', 'name' => 'Palau'],
            ['code' => 'PA', 'name' => 'Pennsylvania'],
            ['code' => 'PR', 'name' => 'Puerto Rico'],
            ['code' => 'RI', 'name' => 'Rhode Island'],
            ['code' => 'SC', 'name' => 'South Carolina'],
            ['code' => 'SD', 'name' => 'South Dakota'],
            ['code' => 'TN', 'name' => 'Tennessee'],
            ['code' => 'TX', 'name' => 'Texas'],
            ['code' => 'UT', 'name' => 'Utah'],
            ['code' => 'VT', 'name' => 'Vermont'],
            ['code' => 'VA', 'name' => 'Virginia'],
            ['code' => 'VI', 'name' => 'Virgin Islands'],
            ['code' => 'WA', 'name' => 'Washington'],
            ['code' => 'WV', 'name' => 'West Virginia'],
            ['code' => 'WI', 'name' => 'Wisconsin'],
            ['code' => 'WY', 'name' => 'Wyoming'],
        ]);

        $br = Country::whereCode('BR')->first();
        $br->regions()->createMany([
            ['code' => 'AC', 'name' => 'Acre'],
            ['code' => 'AL', 'name' => 'Alagoas'],
            ['code' => 'AP', 'name' => 'Amapá'],
            ['code' => 'AM', 'name' => 'Amazonas'],
            ['code' => 'BA', 'name' => 'Bahia'],
            ['code' => 'CE', 'name' => 'Ceará'],
            ['code' => 'DF', 'name' => 'Distrito Federal'],
            ['code' => 'ES', 'name' => 'Espírito Santo'],
            ['code' => 'GO', 'name' => 'Goiás'],
            ['code' => 'MA', 'name' => 'Maranhão'],
            ['code' => 'MT', 'name' => 'Mato Grosso'],
            ['code' => 'MS', 'name' => 'Mato Grosso do Sul'],
            ['code' => 'MG', 'name' => 'Minas Gerais'],
            ['code' => 'PA', 'name' => 'Pará'],
            ['code' => 'PB', 'name' => 'Paraíba'],
            ['code' => 'PR', 'name' => 'Paraná'],
            ['code' => 'PE', 'name' => 'Pernambuco'],
            ['code' => 'PI', 'name' => 'Piauí'],
            ['code' => 'RJ', 'name' => 'Rio de Janeiro'],
            ['code' => 'RN', 'name' => 'Rio Grande do Norte'],
            ['code' => 'RS', 'name' => 'Rio Grande do Sul'],
            ['code' => 'RO', 'name' => 'Rondônia'],
            ['code' => 'RR', 'name' => 'Roraima'],
            ['code' => 'SC', 'name' => 'Santa Catarina'],
            ['code' => 'SP', 'name' => 'São Paulo'],
            ['code' => 'SE', 'name' => 'Sergipe'],
            ['code' => 'TO', 'name' => 'Tocantins'],
        ]);

        $ca = Country::whereCode('CA')->first();
        $ca->regions()->createMany([
            ['code' => 'AB', 'name' => 'Alberta'],
            ['code' => 'BC', 'name' => 'British Columbia'],
            ['code' => 'MB', 'name' => 'Manitoba'],
            ['code' => 'NB', 'name' => 'New Brunswick'],
            ['code' => 'NL', 'name' => 'Newfoundland and Labrador'],
            ['code' => 'NT', 'name' => 'Northwest Territories'],
            ['code' => 'NS', 'name' => 'Nova Scotia'],
            ['code' => 'NU', 'name' => 'Nunavut'],
            ['code' => 'ON', 'name' => 'Ontario'],
            ['code' => 'PE', 'name' => 'Prince Edward Island'],
            ['code' => 'QC', 'name' => 'Quebec'],
            ['code' => 'SK', 'name' => 'Saskatchewan'],
            ['code' => 'YT', 'name' => 'Yukon'],
        ]);

        $ca = Country::whereCode('CH')->first();
        $ca->regions()->createMany([
            ['code' => 'AG', 'name' => 'Aargau'],
            ['code' => 'AI', 'name' => 'Appenzell Innerrhoden'],
            ['code' => 'AR', 'name' => 'Appenzell Ausserrhoden'],
            ['code' => 'BE', 'name' => 'Bern'],
            ['code' => 'BL', 'name' => 'Basel-Landschaft'],
            ['code' => 'BS', 'name' => 'Basel-Stadt'],
            ['code' => 'FR', 'name' => 'Fribourg'],
            ['code' => 'GE', 'name' => 'Genève'],
            ['code' => 'GL', 'name' => 'Glarus'],
            ['code' => 'GR', 'name' => 'Graubünden'],
            ['code' => 'JU', 'name' => 'Jura'],
            ['code' => 'LU', 'name' => 'Luzern'],
            ['code' => 'NE', 'name' => 'Neuchâtel'],
            ['code' => 'NW', 'name' => 'Nidwalden'],
            ['code' => 'OW', 'name' => 'Obwalden'],
            ['code' => 'SG', 'name' => 'St. Gallen'],
            ['code' => 'SO', 'name' => 'Solothurn'],
            ['code' => 'SZ', 'name' => 'Schwyz'],
            ['code' => 'TG', 'name' => 'Thurgau'],
            ['code' => 'TI', 'name' => 'Ticino'],
            ['code' => 'UR', 'name' => 'Uri'],
            ['code' => 'VD', 'name' => 'Vaud'],
            ['code' => 'VS', 'name' => 'Valais'],
            ['code' => 'ZG', 'name' => 'Zug'],
            ['code' => 'ZH', 'name' => 'Zürich'],
        ]);

        $au = Country::whereCode('AU')->first();
        $au->regions()->createMany([
            ['code' => 'NSW', 'name' => 'New South Wales'],
            ['code' => 'QLD', 'name' => 'Queensland'],
            ['code' => 'SA', 'name' => 'South Australia'],
            ['code' => 'TAS', 'name' => 'Tasmania'],
            ['code' => 'VIC', 'name' => 'Victoria'],
            ['code' => 'WA', 'name' => 'Western Australia'],
            ['code' => 'NT', 'name' => 'Northern Territory'],
            ['code' => 'ACT', 'name' => 'Australian Capital Territory'],
        ]);

        $de = Country::whereCode('DE')->first();
        $de->regions()->createMany([
            ['code' => 'BW', 'name' => 'Baden-Württemberg'],
            ['code' => 'BY', 'name' => 'Bayern'],
            ['code' => 'BE', 'name' => 'Berlin'],
            ['code' => 'BB', 'name' => 'Brandenburg'],
            ['code' => 'HB', 'name' => 'Bremen'],
            ['code' => 'HH', 'name' => 'Hamburg'],
            ['code' => 'HE', 'name' => 'Hessen'],
            ['code' => 'MV', 'name' => 'Mecklenburg-Vorpommern'],
            ['code' => 'NI', 'name' => 'Niedersachsen'],
            ['code' => 'NW', 'name' => 'Nordrhein-Westfalen'],
            ['code' => 'RP', 'name' => 'Rheinland-Pfalz'],
            ['code' => 'SL', 'name' => 'Saarland'],
            ['code' => 'SN', 'name' => 'Sachsen'],
            ['code' => 'ST', 'name' => 'Sachsen-Anhalt'],
            ['code' => 'SH', 'name' => 'Schleswig-Holstein'],
            ['code' => 'TH', 'name' => 'Thüringen'],
        ]);

        $ee = Country::whereCode('EE')->first();
        $ee->regions()->createMany([
            ['code' => 'HA', 'name' => 'Harju'],
            ['code' => 'HI', 'name' => 'Hiiu'],
            ['code' => 'IV', 'name' => 'Ida-Viru'],
            ['code' => 'JR', 'name' => 'Jõgeva'],
            ['code' => 'JN', 'name' => 'Järva'],
            ['code' => 'LN', 'name' => 'Lääne'],
            ['code' => 'LV', 'name' => 'Lääne-Viru'],
            ['code' => 'PL', 'name' => 'Põlva'],
            ['code' => 'PR', 'name' => 'Pärnu'],
            ['code' => 'RA', 'name' => 'Rapla'],
            ['code' => 'SA', 'name' => 'Saare'],
            ['code' => 'TA', 'name' => 'Tartu'],
            ['code' => 'VG', 'name' => 'Valga'],
            ['code' => 'VD', 'name' => 'Viljandi'],
            ['code' => 'VR', 'name' => 'Võru'],
        ]);

        $ie = Country::whereCode('IE')->first();
        $ie->regions()->createMany([
            ['code' => 'D', 'name' => 'Dublin'],
            ['code' => 'WW', 'name' => 'Wicklow'],
            ['code' => 'WX', 'name' => 'Wexford'],
            ['code' => 'CW', 'name' => 'Carlow'],
            ['code' => 'KE', 'name' => 'Kildare'],
            ['code' => 'MH', 'name' => 'Meath'],
            ['code' => 'LH', 'name' => 'Louth'],
            ['code' => 'MN', 'name' => 'Monaghan'],
            ['code' => 'CN', 'name' => 'Cavan'],
            ['code' => 'LD', 'name' => 'Longford'],
            ['code' => 'WH', 'name' => 'Westmeath'],
            ['code' => 'OY', 'name' => 'Offaly'],
            ['code' => 'LS', 'name' => 'Laois'],
            ['code' => 'KK', 'name' => 'Kilkenny'],
            ['code' => 'WD', 'name' => 'Waterford'],
            ['code' => 'C', 'name' => 'Cork'],
            ['code' => 'KY', 'name' => 'Kerry'],
            ['code' => 'LK', 'name' => 'Limerick'],
            ['code' => 'TN', 'name' => 'North Tipperary'],
            ['code' => 'TS', 'name' => 'South Tipperary'],
            ['code' => 'CE', 'name' => 'Clare'],
            ['code' => 'G', 'name' => 'Galway'],
            ['code' => 'MO', 'name' => 'Mayo'],
            ['code' => 'RN', 'name' => 'Roscommon'],
            ['code' => 'SO', 'name' => 'Sligo'],
            ['code' => 'LM', 'name' => 'Leitrim'],
            ['code' => 'DL', 'name' => 'Donegal'],
        ]);

        $nl = Country::whereCode('NL')->first();
        $nl->regions()->createMany([
            ['code' => 'DR', 'name' => 'Drenthe'],
            ['code' => 'FL', 'name' => 'Flevoland'],
            ['code' => 'FR', 'name' => 'Friesland'],
            ['code' => 'GE', 'name' => 'Gelderland'],
            ['code' => 'GR', 'name' => 'Groningen'],
            ['code' => 'LI', 'name' => 'Limburg'],
            ['code' => 'NB', 'name' => 'Noord-Brabant'],
            ['code' => 'NH', 'name' => 'Noord-Holland'],
            ['code' => 'OV', 'name' => 'Overijssel'],
            ['code' => 'UT', 'name' => 'Utrecht'],
            ['code' => 'ZE', 'name' => 'Zeeland'],
            ['code' => 'ZH', 'name' => 'Zuid-Holland'],
        ]);

        $gb = Country::whereCode('GB')->first();
        $gb->regions()->createMany([
            ['code' => 'ABE', 'name' => 'Aberdeenshire'],
            ['code' => 'ALY', 'name' => 'Anglesey'],
            ['code' => 'ANG', 'name' => 'Angus'],
            ['code' => 'ARG', 'name' => 'Argyll'],
            ['code' => 'AYR', 'name' => 'Ayrshire'],
            ['code' => 'BAN', 'name' => 'Banffshire'],
            ['code' => 'BED', 'name' => 'Bedfordshire'],
            ['code' => 'BER', 'name' => 'Berkshire'],
            ['code' => 'BWS', 'name' => 'Berwickshire'],
            ['code' => 'BRE', 'name' => 'Brecknockshire'],
            ['code' => 'BUC', 'name' => 'Buckinghamshire'],
            ['code' => 'BUT', 'name' => 'Bute'],
            ['code' => 'CAE', 'name' => 'Caernarfonshire'],
            ['code' => 'CAI', 'name' => 'Caithness'],
            ['code' => 'CAM', 'name' => 'Cambridgeshire'],
            ['code' => 'CAR', 'name' => 'Cardiganshire'],
            ['code' => 'CMS', 'name' => 'Carmarthenshire'],
            ['code' => 'CHE', 'name' => 'Cheshire'],
            ['code' => 'CLA', 'name' => 'Clackmannanshire'],
            ['code' => 'CLE', 'name' => 'Cleveland'],
            ['code' => 'COR', 'name' => 'Cornwall'],
            ['code' => 'CRO', 'name' => 'Cromartyshire'],
            ['code' => 'CBR', 'name' => 'Cumberland'],
            ['code' => 'CUM', 'name' => 'Cumbria'],
            ['code' => 'DEN', 'name' => 'Denbighshire'],
            ['code' => 'DER', 'name' => 'Derbyshire'],
            ['code' => 'DEV', 'name' => 'Devon'],
            ['code' => 'DOR', 'name' => 'Dorset'],
            ['code' => 'DBS', 'name' => 'Dumbartonshire'],
            ['code' => 'DUM', 'name' => 'Dumfriesshire'],
            ['code' => 'DUR', 'name' => 'Durham'],
            ['code' => 'ELO', 'name' => 'East Lothian'],
            ['code' => 'ESS', 'name' => 'Essex'],
            ['code' => 'FLI', 'name' => 'Flintshire'],
            ['code' => 'FIF', 'name' => 'Fife'],
            ['code' => 'GLA', 'name' => 'Glamorgan'],
            ['code' => 'GLO', 'name' => 'Gloucestershire'],
            ['code' => 'HAM', 'name' => 'Hampshire'],
            ['code' => 'HER', 'name' => 'Herefordshire'],
            ['code' => 'HTF', 'name' => 'Hertfordshire'],
            ['code' => 'HUN', 'name' => 'Huntingdonshire'],
            ['code' => 'INV', 'name' => 'Inverness'],
            ['code' => 'KEN', 'name' => 'Kent'],
            ['code' => 'KCD', 'name' => 'Kincardineshire'],
            ['code' => 'KIN', 'name' => 'Kinross-shire'],
            ['code' => 'KIR', 'name' => 'Kirkcudbrightshire'],
            ['code' => 'LKS', 'name' => 'Lanarkshire'],
            ['code' => 'LAN', 'name' => 'Lancashire'],
            ['code' => 'LEI', 'name' => 'Leicestershire'],
            ['code' => 'LIN', 'name' => 'Lincolnshire'],
            ['code' => 'LON', 'name' => 'London'],
            ['code' => 'MAN', 'name' => 'Manchester'],
            ['code' => 'MER', 'name' => 'Merionethshire'],
            ['code' => 'MSY', 'name' => 'Merseyside'],
            ['code' => 'MDX', 'name' => 'Middlesex'],
            ['code' => 'MID', 'name' => 'Midlands'],
            ['code' => 'MLT', 'name' => 'Midlothian'],
            ['code' => 'MON', 'name' => 'Monmouthshire'],
            ['code' => 'MGY', 'name' => 'Montgomeryshire'],
            ['code' => 'MOR', 'name' => 'Moray'],
            ['code' => 'NAI', 'name' => 'Nairnshire'],
            ['code' => 'NOR', 'name' => 'Norfolk'],
            ['code' => 'NMP', 'name' => 'Northamptonshire'],
            ['code' => 'NUM', 'name' => 'Northumberland'],
            ['code' => 'NOT', 'name' => 'Nottinghamshire'],
            ['code' => 'ORK', 'name' => 'Orkney'],
            ['code' => 'OXF', 'name' => 'Oxfordshire'],
            ['code' => 'PEE', 'name' => 'Peebleshire'],
            ['code' => 'PEM', 'name' => 'Pembrokeshire'],
            ['code' => 'PER', 'name' => 'Perthshire'],
            ['code' => 'RAD', 'name' => 'Radnorshire'],
            ['code' => 'REN', 'name' => 'Renfrewshire'],
            ['code' => 'ROS', 'name' => 'Ross & Cromarty'],
            ['code' => 'ROX', 'name' => 'Roxburghshire'],
            ['code' => 'RUT', 'name' => 'Rutland'],
            ['code' => 'SEL', 'name' => 'Selkirkshire'],
            ['code' => 'SHE', 'name' => 'Shetland'],
            ['code' => 'SHR', 'name' => 'Shropshire'],
            ['code' => 'SOM', 'name' => 'Somerset'],
            ['code' => 'STA', 'name' => 'Staffordshire'],
            ['code' => 'STI', 'name' => 'Stirlingshire'],
            ['code' => 'SUF', 'name' => 'Suffolk'],
            ['code' => 'SUR', 'name' => 'Surrey'],
            ['code' => 'SUS', 'name' => 'Sussex'],
            ['code' => 'SUT', 'name' => 'Sutherland'],
            ['code' => 'TYN', 'name' => 'Tyne & Wear'],
            ['code' => 'WAR', 'name' => 'Warwickshire'],
            ['code' => 'WLO', 'name' => 'West Lothian'],
            ['code' => 'WES', 'name' => 'Westmorland'],
            ['code' => 'WIG', 'name' => 'Wigtownshire'],
            ['code' => 'WIL', 'name' => 'Wiltshire'],
            ['code' => 'WOR', 'name' => 'Worcestershire'],
            ['code' => 'YOR', 'name' => 'Yorkshire'],
        ]);

        $ro = Country::whereCode('RO')->first();
        $ro->regions()->createMany([
            ['code' => 'AB', 'name' => 'Alba'],
            ['code' => 'AR', 'name' => 'Arad'],
            ['code' => 'AG', 'name' => 'Arges'],
            ['code' => 'BC', 'name' => 'Bacău'],
            ['code' => 'BH', 'name' => 'Bihor'],
            ['code' => 'BN', 'name' => 'Bistrita - Nasaud Bistrita'],
            ['code' => 'BT', 'name' => 'Botosani'],
            ['code' => 'BV', 'name' => 'Brasov'],
            ['code' => 'BR', 'name' => 'Braila'],
            ['code' => 'B', 'name' => 'Bucuresti'],
            ['code' => 'BZ', 'name' => 'Buzau'],
            ['code' => 'CS', 'name' => 'Caras - Severin'],
            ['code' => 'CL', 'name' => 'Calarasi'],
            ['code' => 'CJ', 'name' => 'Cluj'],
            ['code' => 'CT', 'name' => 'Constanta'],
            ['code' => 'CV', 'name' => 'Covasna Sfantu Gheorghe'],
            ['code' => 'DB', 'name' => 'Dambovita'],
            ['code' => 'DJ', 'name' => 'Dolj'],
            ['code' => 'GL', 'name' => 'Galati'],
            ['code' => 'GR', 'name' => 'Giurgiu'],
            ['code' => 'GJ', 'name' => 'Gorj'],
            ['code' => 'HR', 'name' => 'Harghita'],
            ['code' => 'HD', 'name' => 'Hunedoara'],
            ['code' => 'IL', 'name' => 'Ialomita'],
            ['code' => 'IS', 'name' => 'Iasi'],
            ['code' => 'IF', 'name' => 'Ilfov'],
            ['code' => 'MM', 'name' => 'Maramures'],
            ['code' => 'MH', 'name' => 'Mehedinti'],
            ['code' => 'MS', 'name' => 'Mures'],
            ['code' => 'NT', 'name' => 'Neamt'],
            ['code' => 'OT', 'name' => 'Olt'],
            ['code' => 'PH', 'name' => 'Prahova Ploiesti'],
            ['code' => 'SM', 'name' => 'Satu Mare'],
            ['code' => 'SJ', 'name' => 'Salaj'],
            ['code' => 'SB', 'name' => 'Sibiu'],
            ['code' => 'SV', 'name' => 'Suceava'],
            ['code' => 'TR', 'name' => 'Teleorman'],
            ['code' => 'TM', 'name' => 'Timis'],
            ['code' => 'TL', 'name' => 'Tulcea'],
            ['code' => 'VS', 'name' => 'Vaslui'],
            ['code' => 'VL', 'name' => 'Valcea'],
            ['code' => 'VN', 'name' => 'Vrancea'],
        ]);

        $hu = Country::whereCode('HU')->first();
        $hu->regions()->createMany([
            ['code' => 'BUD', 'name' => 'Budapest'],
            ['code' => 'BAR', 'name' => 'Baranya'],
            ['code' => 'BKM', 'name' => 'Bács-Kiskun'],
            ['code' => 'BEK', 'name' => 'Békés'],
            ['code' => 'BAZ', 'name' => 'Borsod-Abaúj-Zemplén'],
            ['code' => 'CSO', 'name' => 'Csongrád'],
            ['code' => 'FEJ', 'name' => 'Fejér'],
            ['code' => 'GMS', 'name' => 'Győr-Moson-Sopron'],
            ['code' => 'HBM', 'name' => 'Hajdú-Bihar'],
            ['code' => 'HEV', 'name' => 'Heves'],
            ['code' => 'JNS', 'name' => 'Jász-Nagykun-Szolnok'],
            ['code' => 'KEM', 'name' => 'Komárom-Esztergom'],
            ['code' => 'NOG', 'name' => 'Nógrád'],
            ['code' => 'PES', 'name' => 'Pest'],
            ['code' => 'SOM', 'name' => 'Somogy'],
            ['code' => 'SSB', 'name' => 'Szabolcs-Szatmár-Bereg'],
            ['code' => 'TOL', 'name' => 'Tolna'],
            ['code' => 'VAS', 'name' => 'Vas'],
            ['code' => 'VES', 'name' => 'Veszprém'],
            ['code' => 'ZAL', 'name' => 'Zala'],
        ]);

        $in = Country::whereCode('IN')->first();
        $in->regions()->createMany([
            ['code' => 'AP', 'name' => 'Andhra Pradesh'],
            ['code' => 'AR', 'name' => 'Arunachal Pradesh'],
            ['code' => 'AS', 'name' => 'Assam'],
            ['code' => 'BR', 'name' => 'Bihar'],
            ['code' => 'CT', 'name' => 'Chhattisgarh'],
            ['code' => 'GA', 'name' => 'Goa'],
            ['code' => 'GJ', 'name' => 'Gujarat'],
            ['code' => 'HR', 'name' => 'Haryana'],
            ['code' => 'HP', 'name' => 'Himachal Pradesh'],
            ['code' => 'JK', 'name' => 'Jammu and Kashmir'],
            ['code' => 'JH', 'name' => 'Jharkhand'],
            ['code' => 'KA', 'name' => 'Karnataka'],
            ['code' => 'KL', 'name' => 'Kerala'],
            ['code' => 'MP', 'name' => 'Madhya Pradesh'],
            ['code' => 'MH', 'name' => 'Maharashtra'],
            ['code' => 'MN', 'name' => 'Manipur'],
            ['code' => 'ML', 'name' => 'Meghalaya'],
            ['code' => 'MZ', 'name' => 'Mizoram'],
            ['code' => 'NL', 'name' => 'Nagaland'],
            ['code' => 'OR', 'name' => 'Odisha'],
            ['code' => 'PB', 'name' => 'Punjab'],
            ['code' => 'RJ', 'name' => 'Rajasthan'],
            ['code' => 'SK', 'name' => 'Sikkim'],
            ['code' => 'TN', 'name' => 'Tamil Nadu'],
            ['code' => 'TG', 'name' => 'Telangana'],
            ['code' => 'TR', 'name' => 'Tripura'],
            ['code' => 'UT', 'name' => 'Uttarakhand'],
            ['code' => 'UP', 'name' => 'Uttar Pradesh'],
            ['code' => 'WB', 'name' => 'West Bengal'],
            ['code' => 'AN', 'name' => 'Andaman and Nicobar Islands'],
            ['code' => 'CH', 'name' => 'Chandigarh'],
            ['code' => 'DN', 'name' => 'Dadra and Nagar Haveli'],
            ['code' => 'DD', 'name' => 'Daman and Diu'],
            ['code' => 'DL', 'name' => 'Delhi'],
            ['code' => 'LD', 'name' => 'Lakshadweep'],
            ['code' => 'PY', 'name' => 'Puducherry'],
        ]);

        $fr = Country::whereCode('FR')->first();
        $fr->regions()->createMany([
            ['code' => 'ARA', 'name' => 'Auvergne-Rhône-Alpes'],
            ['code' => 'BFC', 'name' => 'Bourgogne-Franche-Comté'],
            ['code' => 'BZH', 'name' => 'Bretagne'],
            ['code' => 'CVL', 'name' => 'Centre–Val-de-Loire'],
            ['code' => 'COR', 'name' => 'Corse'],
            ['code' => 'GP', 'name' => 'Guadeloupe'],
            ['code' => 'GF', 'name' => 'Guyane'],
            ['code' => 'GE', 'name' => 'Grand-Est'],
            ['code' => 'HF', 'name' => 'Hauts-de-France'],
            ['code' => 'IDF', 'name' => 'Île-de-France'],
            ['code' => 'MQ', 'name' => 'Martinique'],
            ['code' => 'YT', 'name' => 'Mayotte'],
            ['code' => 'NOR', 'name' => 'Normandie'],
            ['code' => 'PL', 'name' => 'Pays-de-la-Loire'],
            ['code' => 'NA', 'name' => 'Nouvelle-Aquitaine'],
            ['code' => 'OCC', 'name' => 'Occitanie'],
            ['code' => 'PACA', 'name' => 'Provence-Alpes-Côte-d\'Azur'],
            ['code' => 'RE', 'name' => 'Réunion'],
        ]);

        $nz = Country::whereCode('NZ')->first();
        $nz->regions()->createMany([
            ['code' => 'NTL', 'name' => 'Northland'],
            ['code' => 'AUK', 'name' => 'Auckland'],
            ['code' => 'WKO', 'name' => 'Waikato'],
            ['code' => 'BOP', 'name' => 'Bay of Plenty'],
            ['code' => 'GIS', 'name' => 'Gisborne'],
            ['code' => 'HKB', 'name' => "Hawke's Bay"],
            ['code' => 'TKI', 'name' => 'Taranaki'],
            ['code' => 'MWT', 'name' => 'Manawatu-Wanganui'],
            ['code' => 'WGN', 'name' => 'Wellington'],
            ['code' => 'TAS', 'name' => 'Tasman'],
            ['code' => 'NSN', 'name' => 'Nelson'],
            ['code' => 'MBH', 'name' => 'Marlborough'],
            ['code' => 'WTC', 'name' => 'West Coast'],
            ['code' => 'CAN', 'name' => 'Canterbury'],
            ['code' => 'OTA', 'name' => 'Otago Otago'],
            ['code' => 'STL', 'name' => 'Southland'],
        ]);

        $es = Country::whereCode('ES')->first();
        $es->regions()->createMany([
            ['code' => 'ES-C', 'name' => 'A Coruña (gl) [La Coruña]'],
            ['code' => 'ES-VI', 'name' => 'Araba (eu)'],
            ['code' => 'ES-AB', 'name' => 'Albacete'],
            ['code' => 'ES-A', 'name' => 'Alacant (ca)'],
            ['code' => 'ES-AL', 'name' => 'Almería'],
            ['code' => 'ES-O', 'name' => 'Asturias'],
            ['code' => 'ES-AV', 'name' => 'Ávila'],
            ['code' => 'ES-BA', 'name' => 'Badajoz'],
            ['code' => 'ES-PM', 'name' => 'Balears (ca) [Baleares]'],
            ['code' => 'ES-B', 'name' => 'Barcelona [Barcelona]'],
            ['code' => 'ES-BU', 'name' => 'Burgos'],
            ['code' => 'ES-CC', 'name' => 'Cáceres'],
            ['code' => 'ES-CA', 'name' => 'Cádiz'],
            ['code' => 'ES-S', 'name' => 'Cantabria'],
            ['code' => 'ES-CS', 'name' => 'Castelló (ca)'],
            ['code' => 'ES-CR', 'name' => 'Ciudad Real'],
            ['code' => 'ES-CO', 'name' => 'Córdoba'],
            ['code' => 'ES-CU', 'name' => 'Cuenca'],
            ['code' => 'ES-GI', 'name' => 'Girona (ca) [Gerona]'],
            ['code' => 'ES-GR', 'name' => 'Granada'],
            ['code' => 'ES-GU', 'name' => 'Guadalajara'],
            ['code' => 'ES-SS', 'name' => 'Gipuzkoa (eu)'],
            ['code' => 'ES-H', 'name' => 'Huelva'],
            ['code' => 'ES-HU', 'name' => 'Huesca'],
            ['code' => 'ES-J', 'name' => 'Jaén'],
            ['code' => 'ES-LO', 'name' => 'La Rioja'],
            ['code' => 'ES-GC', 'name' => 'Las Palmas'],
            ['code' => 'ES-LE', 'name' => 'León'],
            ['code' => 'ES-L', 'name' => 'Lleida (ca) [Lérida]'],
            ['code' => 'ES-LU', 'name' => 'Lugo (gl) [Lugo]'],
            ['code' => 'ES-M', 'name' => 'Madrid'],
            ['code' => 'ES-MA', 'name' => 'Málaga'],
            ['code' => 'ES-MU', 'name' => 'Murcia'],
            ['code' => 'ES-NA', 'name' => 'Nafarroa (eu)'],
            ['code' => 'ES-OR', 'name' => 'Ourense (gl) [Orense]'],
            ['code' => 'ES-P', 'name' => 'Palencia'],
            ['code' => 'ES-PO', 'name' => 'Pontevedra (gl) [Pontevedra]'],
            ['code' => 'ES-SA', 'name' => 'Salamanca'],
            ['code' => 'ES-TF', 'name' => 'Santa Cruz de Tenerife'],
            ['code' => 'ES-SG', 'name' => 'Segovia'],
            ['code' => 'ES-SE', 'name' => 'Sevilla'],
            ['code' => 'ES-SO', 'name' => 'Soria'],
            ['code' => 'ES-T', 'name' => 'Tarragona (ca) [Tarragona]'],
            ['code' => 'ES-TE', 'name' => 'Teruel'],
            ['code' => 'ES-TO', 'name' => 'Toledo'],
            ['code' => 'ES-V', 'name' => 'València (ca)'],
            ['code' => 'ES-VA', 'name' => 'Valladolid'],
            ['code' => 'ES-BI', 'name' => 'Bizkaia (eu)'],
            ['code' => 'ES-ZA', 'name' => 'Zamora'],
            ['code' => 'ES-Z', 'name' => 'Zaragoza'],
        ]);

        $mx = Country::whereCode('MX')->first();
        $mx->regions()->createMany([
            ['code' => 'MX-AGU', 'name' => 'Aguascalientes'],
            ['code' => 'MX-BCN', 'name' => 'Baja California'],
            ['code' => 'MX-BCS', 'name' => 'Baja California Sur'],
            ['code' => 'MX-CAM', 'name' => 'Campeche'],
            ['code' => 'MX-CHP', 'name' => 'Chiapas'],
            ['code' => 'MX-CHH', 'name' => 'Chihuahua'],
            ['code' => 'MX-COA', 'name' => 'Coahuila'],
            ['code' => 'MX-COL', 'name' => 'Colima'],
            ['code' => 'MX-CMX', 'name' => 'Ciudad de México'],
            ['code' => 'MX-DUR', 'name' => 'Durango'],
            ['code' => 'MX-GUA', 'name' => 'Guanajuato'],
            ['code' => 'MX-GRO', 'name' => 'Guerrero'],
            ['code' => 'MX-HID', 'name' => 'Hidalgo'],
            ['code' => 'MX-JAL', 'name' => 'Jalisco'],
            ['code' => 'MX-MEX', 'name' => 'Estado de México'],
            ['code' => 'MX-MIC', 'name' => 'Michoacán'],
            ['code' => 'MX-MOR', 'name' => 'Morelos'],
            ['code' => 'MX-NAY', 'name' => 'Nayarit'],
            ['code' => 'MX-NLE', 'name' => 'Nuevo León'],
            ['code' => 'MX-OAX', 'name' => 'Oaxaca'],
            ['code' => 'MX-PUE', 'name' => 'Puebla'],
            ['code' => 'MX-QUE', 'name' => 'Querétaro'],
            ['code' => 'MX-ROO', 'name' => 'Quintana Roo'],
            ['code' => 'MX-SLP', 'name' => 'San Luis Potosí'],
            ['code' => 'MX-SIN', 'name' => 'Sinaloa'],
            ['code' => 'MX-SON', 'name' => 'Sonora'],
            ['code' => 'MX-TAB', 'name' => 'Tabasco'],
            ['code' => 'MX-TAM', 'name' => 'Tamaulipas'],
            ['code' => 'MX-TLA', 'name' => 'Tlaxcala'],
            ['code' => 'MX-VER', 'name' => 'Veracruz'],
            ['code' => 'MX-YUC', 'name' => 'Yucatán'],
            ['code' => 'MX-ZAC', 'name' => 'Zacatecas'],
        ]);

        $mx = Country::whereCode('SI')->first();
        $mx->regions()->createMany([
            ['code' => 'SI.DO', 'name' => 'Dolenjska'],
            ['code' => 'SI.GO', 'name' => 'Gorenjska'],
            ['code' => 'SI.SP', 'name' => 'Goriška'],
            ['code' => 'SI.KO', 'name' => 'Koroška'],
            ['code' => 'SI.NO', 'name' => 'Notranjsko-kraška'],
            ['code' => 'SI.JP', 'name' => 'Obalno-kraška'],
            ['code' => 'SI.LJ', 'name' => 'Osrednjeslovenska'],
            ['code' => 'SI.PD', 'name' => 'Podravska'],
            ['code' => 'SI.PM', 'name' => 'Pomurska'],
            ['code' => 'SI.SA', 'name' => 'Savinjska'],
            ['code' => 'SI.PS', 'name' => 'Spodnjeposavska'],
            ['code' => 'SI.ZS', 'name' => 'Zasavska'],
        ]);

        $mx = Country::whereCode('RU')->first();
        $mx->regions()->createMany([
            ['code' => 'RU-MOW', 'name' => 'Москва'],
            ['code' => 'RU-MOS', 'name' => 'Московская область'],
            ['code' => 'RU-SPE', 'name' => 'Санкт-Петербург'],
            ['code' => 'RU-AMU', 'name' => 'Амурская область'],
            ['code' => 'RU-ARK', 'name' => 'Архангельская область'],
            ['code' => 'RU-AST', 'name' => 'Астраханская область'],
            ['code' => 'RU-BEL', 'name' => 'Белгородская область'],
            ['code' => 'RU-BRY', 'name' => 'Брянская область'],
            ['code' => 'RU-VLA', 'name' => 'Владимирская область'],
            ['code' => 'RU-VGG', 'name' => 'Волгоградская область'],
            ['code' => 'RU-VLG', 'name' => 'Вологодская область'],
            ['code' => 'RU-VOR', 'name' => 'Воронежская область'],
            ['code' => 'RU-IVA', 'name' => 'Ивановская область'],
            ['code' => 'RU-IRK', 'name' => 'Иркутская область'],
            ['code' => 'RU-KGD', 'name' => 'Калининградская область'],
            ['code' => 'RU-KLU', 'name' => 'Калужская область'],
            ['code' => 'RU-KEM', 'name' => 'Кемеровская область'],
            ['code' => 'RU-KIR', 'name' => 'Кировская область'],
            ['code' => 'RU-KOS', 'name' => 'Костромская область'],
            ['code' => 'RU-KGN', 'name' => 'Курганская область'],
            ['code' => 'RU-KRS', 'name' => 'Курская область'],
            ['code' => 'RU-LEN', 'name' => 'Ленинградская область'],
            ['code' => 'RU-LIP', 'name' => 'Липецкая область'],
            ['code' => 'RU-MAG', 'name' => 'Магаданская область'],
            ['code' => 'RU-MUR', 'name' => 'Мурманская область'],
            ['code' => 'RU-NIZ', 'name' => 'Нижегородская область'],
            ['code' => 'RU-NGR', 'name' => 'Новгородская область'],
            ['code' => 'RU-NVS', 'name' => 'Новосибирская область'],
            ['code' => 'RU-OMS', 'name' => 'Омская область'],
            ['code' => 'RU-ORE', 'name' => 'Оренбургская область'],
            ['code' => 'RU-ORL', 'name' => 'Орловская область'],
            ['code' => 'RU-PNZ', 'name' => 'Пензенская область'],
            ['code' => 'RU-PSK', 'name' => 'Псковская область'],
            ['code' => 'RU-ROS', 'name' => 'Ростовская область'],
            ['code' => 'RU-RYA', 'name' => 'Рязанская область'],
            ['code' => 'RU-SAM', 'name' => 'Самарская область'],
            ['code' => 'RU-SAR', 'name' => 'Саратовская область'],
            ['code' => 'RU-SAK', 'name' => 'Сахалинская область'],
            ['code' => 'RU-SVE', 'name' => 'Свердловская область'],
            ['code' => 'RU-SMO', 'name' => 'Смоленская область'],
            ['code' => 'RU-TAM', 'name' => 'Тамбовская область'],
            ['code' => 'RU-TVE', 'name' => 'Тверская область'],
            ['code' => 'RU-TOM', 'name' => 'Томская область'],
            ['code' => 'RU-TUL', 'name' => 'Тульская область'],
            ['code' => 'RU-TYU', 'name' => 'Тюменская область'],
            ['code' => 'RU-ULY', 'name' => 'Ульяновская область'],
            ['code' => 'RU-CHE', 'name' => 'Челябинская область'],
            ['code' => 'RU-YAR', 'name' => 'Ярославская область'],
            ['code' => 'RU-AD', 'name' => 'Адыгея'],
            ['code' => 'RU-BA', 'name' => 'Башкортостан'],
            ['code' => 'RU-BU', 'name' => 'Бурятия'],
            ['code' => 'RU-DA', 'name' => 'Дагестан'],
            ['code' => 'RU-IN', 'name' => 'Ингушетия'],
            ['code' => 'RU-KB', 'name' => 'Кабардино-Балкария'],
            ['code' => 'RU-KL', 'name' => 'Калмыкия'],
            ['code' => 'RU-KC', 'name' => 'Карачаево-Черкесия'],
            ['code' => 'RU-KR', 'name' => 'Карелия'],
            ['code' => 'RU-ME', 'name' => 'Марий Эл'],
            ['code' => 'RU-MO', 'name' => 'Мордовия'],
            ['code' => 'RU-AL', 'name' => 'Республика Алтай'],
            ['code' => 'RU-KO', 'name' => 'Республика Коми'],
            ['code' => 'RU-SA', 'name' => 'Якутия'],
            ['code' => 'RU-SE', 'name' => 'Северная Осетия'],
            ['code' => 'RU-TA', 'name' => 'Татарстан'],
            ['code' => 'RU-TY', 'name' => 'Тыва'],
            ['code' => 'RU-UD', 'name' => 'Удмуртия'],
            ['code' => 'RU-KK', 'name' => 'Хакасия'],
            ['code' => 'RU-CE', 'name' => 'Чечня'],
            ['code' => 'RU-CU', 'name' => 'Чувашия'],
            ['code' => 'RU-ALT', 'name' => 'Алтайский край'],
            ['code' => 'RU-ZAB', 'name' => 'Забайкальский край'],
            ['code' => 'RU-KAM', 'name' => 'Камчатский край'],
            ['code' => 'RU-KDA', 'name' => 'Краснодарский край'],
            ['code' => 'RU-KYA', 'name' => 'Красноярский край'],
            ['code' => 'RU-PER', 'name' => 'Пермский край'],
            ['code' => 'RU-PRI', 'name' => 'Приморский край'],
            ['code' => 'RU-STA', 'name' => 'Ставропольский край'],
            ['code' => 'RU-KHA', 'name' => 'Хабаровский край'],
            ['code' => 'RU-NEN', 'name' => 'Ненецкий автономный округ'],
            ['code' => 'RU-KHM', 'name' => 'Ханты-Мансийский автономный округ'],
            ['code' => 'RU-CHU', 'name' => 'Чукотский автономный округ'],
            ['code' => 'RU-YAN', 'name' => 'Ямало-Ненецкий автономный округ'],
            ['code' => 'RU-YEV', 'name' => 'Еврейская автономная область'],
        ]);

    }
}
